name: Deploy Web App to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the main branch
      - uses: actions/checkout@v4

      # sets up .NET Core SDK 10.0.x
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # Install wasm-tools
      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      # publishes Blazor project to the prerender/output folder
      - name: Publish .NET Core Project
        run: dotnet publish src/EventInvitations.Blazor/EventInvitations.Blazor.csproj -c Release -o prerender/output --nologo

      # Setup latest Chrome for prerendering to avoid old Puppeteer Chromium
      # - name: Setup Chrome
      #  id: chrome
      #  uses: browser-actions/setup-chrome@v1
      #  with:
      #    chrome-version: stable

      # Use NodeJS react-snap utility to prerender static website with modern Chrome
      # - name: Prerender Blazor client
      #  working-directory: prerender
      #  env:
      #    PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
      #  run: npx react-snap

      # Extract repo name from GITHUB_REPOSITORY environment variable
      - name: Extract repo name
        shell: bash
        run: echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_ENV

      # change base tag in all html files to include subfolder
      - name: Change base tag
        working-directory: prerender/output/wwwroot
        run: |
          find . -name "*.html" | while read htmlFile; do
              sed -i 's/<base href="\/"/<base href="\/${{ env.REPO_NAME }}\/"/g' $htmlFile
              sed -i 's/mud-drawer-close-responsive-md-left/mud-drawer-open-responsive-md-left/g' $htmlFile
              sed -i 's/mud-drawer--closed/mud-drawer--open/g' $htmlFile
          done

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch prerender/output/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: deployment-branch
          folder: prerender/output/wwwroot